services:
  redis:
    image: bitnami/redis-cluster:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
